apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  source:
    repoURL: https://github.com/Ravelin/argocd-helm-go-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
