apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cti
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    chart: php-chart
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://gitlab.example.com/api/v4/projects/41416438/packages/helm/stable.git
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
