apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  source:
    chart: grafana
    helm:
      values: |
        persistence:
          enabled: true
          type: pvc
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          storageClassName: "standard"
        adminPassword: {{ .Values.spec.source.helm.values.adminPassword }}
        service:
          type: NodePort
          nodePort: 30001
    repoURL: https://grafana.github.io/helm-charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
