apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  source:
    chart: grafana
    helm:
      values: |
        persistence:
          enabled: true
          type: pvc
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          storageClassName: "standard"
        ingress:
          enabled: {{ .Values.grafana.ingress.enabled }}
          annotations:
            kubernetes.io/ingress.class: {{ .Values.grafana.ingress.class }}
          hosts:
            - {{ .Values.grafana.ingress.host }}
        adminUser: admin
        adminPassword: {{ .Values.spec.source.helm.values.adminPassword }}
    repoURL: https://grafana.github.io/helm-charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
