apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  source:
    chart: grafana
    helm:
      values: |
        replicas: 1
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - grafana.example.com
        adminUser: admin
        adminPassword: admin
    repoURL: https://grafana.github.io/helm-charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
